Menpha/urls.py
from django.conf.urls import patterns, include, url
from . import views

from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	# For Admin Page
    url(r'^admin/', include(admin.site.urls)),

    # intro page
    url(r'^', include('main.urls'), name='intro'),

    # Sitewide Statics
    url(r'^about-menpha/$', views.about, name='about'),

    url(r'^contact-menpha/', views.contact, name='contact'),

    url(r'^privacy-terms/', views.privacy, name='privacy'),

    url(r'^team-menpha/', views.team, name='team'),

    url(r'^learn-menpha/', views.start, name='start'),

    url(r'^story-behind/', views.story, name='story'),

    url(r'^faq/', views.faq, name='faq'),

    url(r'^donate/', views.donate, name='donate'),

    url(r'^technology/', views.technology, name='technology'),

    url(r'^developer/', views.developer, name='developer'),
)

# Registration Backend
urlpatterns += patterns('',

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
)
# Robot.txt - Without, lots of emails as error cos of hits from google bot
urlpatterns += patterns('',
    (r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
)

main/urls.py
# Urls.py Handwritten by google.com/+Nkansahrexford
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import views
from django.conf.urls.static import static
from Menpha import settings

urlpatterns = patterns('',
    # See Menpha.urls for other URLs
    url(r'^$', views.intro_page, name='intro'),

    url(r'^app/$', views.app_home, name='home'),

    url(r'^app/search/$', views.search, name='search'),

    url(r'^app/add/$', views.CreateImei.as_view(), name='add'),

    url(r'^app/detail/(?P<slug>\d+)/$', views.imei_detail, name='detail'),

    url(r'^app/edit/(?P<slug>\d+)/$', views.UpdateImei.as_view(), name='edit'),

    url(r'^app/notify/(?P<slug>\d+)/$', views.notify, name='notify'),

    url(r'^app/notify/thanks/$', login_required(TemplateView.as_view(template_name='notify-thanks.html')),),
    url(r'^app/email/thanks/$', login_required(TemplateView.as_view(template_name='email-thanks.html')),),
	
    url(r'^app/delete/(?P<slug>\d+)/$', views.DeleteImei.as_view(), name='delete'),

	url(r'^app/my-list/', views.ListImei.as_view(), name='myList'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# Models.py Handwritten by google.com/+Nkansahrexford
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from django.contrib.auth.models import User

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Item(models.Model):
	""" Main model for the Menpha app. """

	TYPE_OF_ITEM = (
		('auto', 'Automobile'),
		('md', 'Mobile Devices'),
		('com', 'Computers'),
		('da', 'Domestic Appliance'),
	)

	STOLEN_OPTION = (
		('ns', 'Its with me'),
		('s', 'Its stolen/missing'),
	)

	device = models.CharField(max_length=250,)
	slug = models.SlugField(max_length=30, unique=True,)
	type_of_item = models.CharField(max_length=20, choices=TYPE_OF_ITEM)
	description = models.TextField()
	stolen = models.CharField(max_length=2, choices=STOLEN_OPTION)
	#photo = models.ImageField(upload_to='devices/', blank=True, null=True)
	photo = ProcessedImageField(blank=True, null=True, upload_to='devices/', processors=[ResizeToFill(250, 250)], format='JPEG', options={'quality': 80})
	pub_date = models.DateTimeField(auto_now=True)
	created_by = models.ForeignKey(User)

	def __unicode__(self):
		""" Returns device name """
		return self.device

	def get_absolute_url(self):
		""" For reverse url matching in views """
		#return reverse('views.search', args=[self.imei])
		return reverse('detail', kwargs={'slug': self.slug})

main/forms.py
# Forms.py Handwritten by google.com/+Nkansahrexford
from django import forms
from django.forms import ModelForm
from main.models import Item
from django.utils.translation import ugettext as _


class ItemForm(ModelForm):
	class Meta:
		model = Item
		fields = ('device', 'slug', 'type_of_item', 'description', 'photo', 'stolen')
		labels = {
			'device': _('Name of the device'),
			'slug': _('Unique Identifier ( IMEI, Serial number, etc )'),
			'type_of_item': _('Select type of'),
			'stolen': _('Indicate state of device'),
			'photo': _('Photo of your device (optional)')
		}

class NotifyForm(forms.Form):
	subject = forms.CharField(max_length=100)
	message = forms.CharField(widget=forms.Textarea)
	#sender = forms.EmailField()
	cc_myself = forms.BooleanField(required=False)

class ContactForm(forms.Form):
	#name = forms.CharField(max_length=100)
	subject = forms.CharField(max_length=300)
	sender = forms.EmailField()
	message = forms.CharField(widget=forms.Textarea)
	cc_myself = forms.BooleanField(required=False)

	#device = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Device name'}))
	#imei = forms.CharField(max_length=15, 
	#	widget=forms.TextInput(attrs={'placeholder':'IMEI '})
	#	)
	#description = forms.CharField(widget=forms.Textarea(
	#	attrs={'placeholder':'Describe device', 
	#			'cols':50,
	#			'rows':4,
	#			'max_length': 350,
	#	}))

Menpha/views.py
from django.shortcuts import render_to_response, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.mail import send_mail
from main.forms import ContactForm

def about(request):
	return render(request, 'about.html')

def contact(request):
	""" Send contact emails """
	if request.method == "POST": # If the form has been submitted...
		form = ContactForm(request.POST) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
		# Process the data in form.cleaned_data
			#name = form.cleaned_data['name']
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			sender = form.cleaned_data['sender']
			cc_myself = form.cleaned_data['cc_myself']
			recipients = ['seanmavley@gmail.com']

			if cc_myself:
				recipients.append(sender)

			send_mail(subject, message, sender, recipients)
			return HttpResponseRedirect('/app/email/thanks/') # Redirect after POST
	else:
		form = ContactForm() # An unbound form
	return render(request, 'contact.html', {'form': form,})

def privacy(request):
	return render(request, 'privacy.html')

def team(request):
	return render(request, 'team.html')

def story(request):
	return render(request, 'story_behind.html')

def start(request):
	return render(request, 'get_started.html')

def faq(request):
	return render(request, 'faq.html')

def donate(request):
	return render(request, 'donate.html')

def technology(request):
	return render(request, 'technology.html')

def developer(request):
	return render(request, 'developer.html')


def file_not_found_404(request):
	return render(request, '404.html')

def server_error(request):
	return render(request, '500.html')

def perm_denied(request):
	return render(request, '403.html')

main/views.py
# Views.py Handwritten by google.com/+Nkansahrexford
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from main.models import Item
from main.forms import ItemForm, NotifyForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
#from django.contrib import messages # Apply later
from django.views.generic import ListView
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


def intro_page(request):
    """Current introductory page in use"""
    return render(request, 'menpha.html')


@login_required
def app_home(request):
    """ App homepage. This page displays the search box """
    return render(request, 'index.html',)


@login_required
def search(request):
    """ Displays results of the searched query"""
    query = request.GET.get('q', '')
    if query:
        qset = Q(slug__iexact=query, stolen__iexact='s')
        results = Item.objects.filter(qset).distinct()
    else:
        results = []

    return render(request, "search.html", {
        'results': results,
        'query': query,
        'user': request.user,  # For checking permission in template
    })


class CreateImei(CreateView):
    """ Adds an object to database by a user in context"""
    template_name = 'add.html'
    form_class = ItemForm
    model = Item

    def form_valid(self, form):
        #save current user into "created_by" field in models.
        form.instance.created_by = self.request.user
        return super(CreateImei, self).form_valid(form)

    @method_decorator(login_required())
    def dispatch(self, * args, ** kwargs):
        return super(CreateImei, self).dispatch(* args, ** kwargs)


class UpdateImei(UpdateView):
    """ Updates an object in context.

    If request.user is same as created_by value in model, dispatch
    fucntion proceeds. Else PermissionDenied. Useful for preventing
    one user from editing item added by another user. """
    model = Item
    fields = ['device', 'slug', 'type_of_item', 'description', 'photo', 'stolen']
    template_name = 'item_form.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        pulled = Item.objects.get(slug=kwargs['slug'])
        if pulled.created_by == request.user:
            return super(UpdateImei, self).dispatch(request, *args, **kwargs)
        raise PermissionDenied

    #@method_decorator(login_required())
    #def dispatch(self, * args, ** kwargs):
    #	return super(UpdateImei, self).dispatch( * args, ** kwargs)


class DeleteImei(DeleteView):
    """ Deletes the the context object.
    If request.user is same as created_by value in model,
    dispatch fucntion proceeds. Else PermissionDenied.

    Useful for preventing one user from deleting
    item added by another user. """
    model = Item
    context_object_name = 'to_delete'
    success_url = reverse_lazy('myList')
    template_name = 'item_confirm_delete.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        grab = Item.objects.get(slug=kwargs['slug'])
        if grab.created_by == request.user:
            return super(DeleteImei, self).dispatch(request, *args, **kwargs)
        raise PermissionDenied


class ListImei(ListView):
    """Lists all the items added by a user."""
    model = Item
    template_name = 'item_list.html'

    def get_queryset(self):
        qset = Q(created_by=self.request.user)
        return Item.objects.filter(qset).distinct().order_by('-pub_date')

    @method_decorator(login_required())
    def dispatch(self, * args, ** kwargs):
        return super(ListImei, self).dispatch(* args, ** kwargs)


@login_required
def imei_detail(request, slug):
    """ Still used to display detail of object. Should be replaced
    with Class Based View DetailView class."""
    s = get_object_or_404(Item, slug=slug)
    return render(request, 'imei-detail.html', {'mylist': s, 'user': request.user})


@login_required
def notify(request, slug):
    """ Send notification email to original owner of device who lost it """
    grab = Item.objects.get(slug=slug)
    if request.method == "POST":  # If the form has been submitted...
        form = NotifyForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
            # Process the data in form.cleaned_data
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = request.user.email
            cc_myself = form.cleaned_data['cc_myself']
            recipients = [grab.created_by.email]

            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/app/notify/thanks/')  # Redirect after POST
    else:
        form = NotifyForm()  # An unbound form
    return render(request, 'send-mail.html', {'form': form, })

main/templates/about.html
{% extends 'menpha.html' %}
{% load static %}
{% load i18n %}

{% block title %} About Menpha Project {% endblock %}

{% block content %}
    <div id="maia-main" role="main">
      <div class="maia-teleport" id="content"></div>
      <div class="project-hero">
        <div class="maia-cols">
          <div class="maia-col-4 hero-img">
            <img alt="Menpha" src="{% static "about.png" %}">
          </div>
          <div class="maia-col-8 hero-content">
            <p>
              {% trans "Learn about Menpha" %}
            </p>
            <h1 class="project-title">
              {% trans "Menpha Project" %}
            </h1>
            <p class="project-organization">
              {% trans "Menpha is an open project, developed by Rexford N." %} 
            </p>
            <p class="project-content">
            {% blocktrans %}
              Menpha Project is a start-up platform developed to use the power of information, provided by humans in solving a real life problem. With our vast storage of details about uniquely-identifiable devices across the world, Menpha is able to give you the right insight should you want to purchase a second-hand item. {% endblocktrans %} <a href="{% url 'start' %}">Learn about the Menpha steps</a>
            
            </p>
            <p class="project-content">
            {% blocktrans %}
              On the other hand, losing a cherished device can be unfortunate. Menpha gives you the opportunity to gently notify millions of persons using our platform daily. You may be then notified by someone somewhere who might come in contact with your item via email through our system. Perhaps the 'thief' will wanna sell off your item or even present it as a gift. You and notify can therefore form the best alliance in union with your local security agency in bringing to book such unscrupulous persons in our communities.
            {% endblocktrans %}
            </p>
            <p class="project-content">
            {% blocktrans %}
              Menpha gets more and more accurate with its growing user-base. Having the most of information about devices globally, we are poised to offer the details to users of our platform.
            {% endblocktrans %}
            </p>
            <p class="project-impact-blurb">
              {% trans "Its everyone's job to help make the world a better and safer place." %}
            </p>
            <div class="hero-footer">
              <img alt="Project logo" src="{% static "hero-logo.png" %}">
              <p class="hero-footer-link">
                <a href="{% url 'developer' %}">{% trans "Contribute Code" %}</a>
              </p>
            </div>
          </div>
        </div>
      </div>
     
    </div>
  {% endblock %}

main/templates/del_success.html
{% extends 'menpha.html' %}
{% block title %} {% trans "Confirm box" %} {% endblock %}
{% load i18n %}

{% block content %}
	<div class="confirmbox">
		<p> {%Truly, you've deleted {{ query }}. </p>
		<span><a href="{% url 'home' %}" class="bbtn blue large">{% trans "Home" %} </a></span>
		<span><a href="{% url 'myList' %}" class="bbtn blue large"> {% trans "My List" %}</a></span>
	</div>
{% endblock %}

main/templates/donate.html
{% extends 'menpha.html' %}
{% load static %}
{% load i18n %}

{% block title %} {% trans "Donate and Support" %} {% endblock %}

{% block content %}
    <div id="maia-main" role="main">
      <div class="maia-teleport" id="content"></div>
      <div class="project-hero">
        <div class="maia-cols">
          <div class="maia-col-4 hero-img">
            <img alt="Donate" src="{% static "donate.jpg" %}">
          </div>
          <div class="maia-col-8 hero-content">
            <p>
              {% trans "Make Menpha Stand" %}
            </p>
            <h1 class="project-title">
              {% trans "Support Menpha Project" %}
            </h1>
            <p class="project-organization">
              {% blocktrans %}
                Menpha Project is determined to serve the global community in the best way possible. Menpha thus relies on your support and help Menpha to rise up to the occasion.
              {% endblocktrans %}
            </p>
            <p class="project-content">
            {% trans "For an overview of the technologies Menpha runs at the backend" %} <a href="{% url 'technology' %}">visit the technology page</a>
            </p>
            <p class="project-content">
              {% trans "Be a part of Menpha Project." %}
            </p>
            <p class="project-impact-blurb">
              {% trans "We are not receiving donations. Support by contributing code. See our developer section to learn more" %}
            </p>           
             <div class="hero-footer">
              <img alt="Project logo" src="{% static "hero-logo.png" %}">
              <p class="hero-footer-link">
                <a href="{% url 'developer' %}">{% trans "Developers" %}</a>
              </p>
            </div>
          </div>
        </div>
      </div>
     
    </div>
  {% endblock %}

main/templates/edit.html
{% extends 'base.html' %}

{% block title %} Edit Item {% endblock %}

{% block notify %}
	Edit your IMEI below. Click 'Save' when done.
{% endblock %}

{% block content %}
	<div class="addbox">
		<form action='.' method='post'>{% csrf_token %}
			{{form.as_p}}
			<input type="submit" class="bbtn large2x blue" role="button" value="Save"/>
		</form>
	</div>
{% endblock %}

main/templates/email-thanks.html
{% extends 'menpha.html' %}
{% load i18n %}
{% block title %} Confirm box {% endblock %}

{% block content %}
	<div class="confirmbox">
		<p> 
		{% blocktrans %}
			<strong>Your message was successfully sent</strong> without any hitches. Thanks for reaching out to Menpha. We will get back to you soon.  
		{% endblocktrans %}
		</p>

		<span><a href="{% url 'home' %}" class="bbtn blue large"> {% trans "Home" %} </a></span>
		<span><a href="{% url 'myList' %}" class="bbtn blue large"> {% trans "My List" %}</a></span>
	</div>
{% endblock %}

main/templates/gplusfollow.html
<center>
    <p>
      <!-- Place this tag where you want the widget to render. -->
      <div class="g-page" data-width="416" data-href="//plus.google.com/103257473583902941951" data-layout="landscape" data-showtagline="false" data-showcoverphoto="false" data-rel="publisher"></div>

      <!-- Place this tag after the last widget tag. -->
      <script type="text/javascript">
        (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/platform.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
      </script>
    </p>
 </center>

main/templates/imei-detail.html
{% extends 'menpha.html' %}
{% load static %}
{% load i18n %}

{% block title %} {{ mylist.device }} detail page {% endblock %}

{% block content %}
	<div class="resultbox {% if mylist.stolen == 'ns' %} not-stolen {% else %} stolen {% endif %}" style="background:url('{% if mylist.photo %}}{{ mylist.photo.url }} {% endif %}') no-repeat bottom right; background-size: 250px 250px;">
		<h3>Details of</h3> 
		<p>
			{{ mylist.slug }}
		</p>
		<h3> Owner </h3>
		<p>
			{{ mylist.created_by }}
		</p>
		<h3>Device name</h3> 
		<p>
			{{ mylist.device }}
		</p>
		<h3>Of type</h3>
		<p>
			{{ mylist.get_type_of_item_display }}
		</p>
		<h3>Description</h3> 
		<p>
			{{ mylist.description }}
		</p>
			<div class="resultoption"> 
			{% if user == mylist.created_by %}
				<span> 
					<a href="/app/delete/{{ mylist.slug }}" class="bbtn red" role="button">Delete</a>
				</span> 
				<span> 
					<a href="/app/edit/{{ mylist.slug }}" class="bbtn blue" role="button">Edit</a>
				</span> 
			{% endif %}
			{% if not user == mylist.created_by %}
				<span>
					<a href="/app/notify/{{ mylist.slug }}" class="bbtn turquoise" role="button"> Notify Owner </a>
				</span>
			{% endif %}
				<span>
					<a onclick="javascript:document.getElementById('overlay').style.display='block';" href="javascript:void(0);" class="bbtn blue" role="button"> Share </a>
				</span>				
				<span>
					Modified {{ mylist.pub_date|timesince }} ago
				</span>			
			</div>
	</div>
{% endblock %}

main/templates/index.html
{% extends 'menpha.html' %}
{% load static %}
{% load i18n %}
{% block title %} Search {% endblock %}

	{% block content %}
		<div class="searchbox">
			<div class="decobox">
				<form class="search" action="/app/search/">
					<input type="text" name="q" required placeholder="Unique Number" maxlength="30" />
					<input type="submit" value="Search" class="bbtn blue large" />
				</form>
			</div>
		</div>
	{% endblock %}

main/templates/item_confirm_delete.html
{% extends 'menpha.html' %}
{% load i18n %}
{% block title %} Confirm box {% endblock %}

{% block notify %}
	<strong style="color:red;">{% trans "NOT REVERSIBLE!" %}</strong> {% trans "Confirm delete of" %}{{ to_delete }}. 
{% endblock %}

{% block content %}
	<div class="confirmbox">
		<form method="post" action="."> {% csrf_token %}
			<p> {% trans "Do you wanna delete" %}{{ to_delete }}? </p>
			<a href="/app/detail/{{ to_delete.slug }}" class="bbtn blue large2x">Don't delete</a>
			<input type="submit" value="Delete" class="bbtn red" />
		</form>
	</div>
{% endblock %}

main/templates/meta.html
<meta charset="utf-8">
<meta name="keywords" content="IMEI, Menpha, Smartphone, Phone, Devices, Gadget, Community, Search, Learn, Add," > 
<meta name="description" content="Community-based IMEI-tagged gadget Tracker. Is the second-hand smartphone you want to purchase stolen or not. My name is Menpha, I can help  you know" > 
<meta name="author" content="Nkansah Rexford google.com/+NkansahRexford" >

main/templates/notify-thanks.html
{% extends 'menpha.html' %}
{% load i18n %}
{% block title %} Confirm box {% endblock %}

{% block content %}
	<div class="confirmbox">
		<p> 
		{% blocktrans %}
			<strong>Your message was successfully sent</strong> without any hitches. The receiver may choose to reply or not. Don't irritate the initial owner of this device. He or she might not even want it again.  
		{% endblocktrans %}
		</p>
		<p>
		{% blocktrans %}
			Should the owner be interested in having the device back, you probably will receive a response to your email, and you can take it from there.
		{% endblocktrans %}
		</p>
		<span><a href="{% url 'home' %}" class="bbtn blue large"> {% trans "Home" %} </a></span>
		<span><a href="{% url 'myList' %}" class="bbtn blue large"> {% trans "My List" %}</a></span>
	</div>
{% endblock %}

main/templates/search.html
{% extends 'menpha.html' %}
{% load i18n %}

{% block title %} Search Results for {{ query }} {% endblock %}

{% block content %}

{% if query %}
	{% if results %}
		{% for mylist in results %}
			<div class="resultbox {% if s.stolen == 'ns' %} not-stolen {% else %} stolen {% endif %}">
				<h3>Unique number match found</h3> 
				<p>
					{{ query }}
				</p>
				<h3>Device name</h3> 
				<p>
					{{ mylist.device }}
				</p>
				<h3>Of type</h3> 
				<p>
					{{ mylist.get_type_of_item_display }}
				</p>
				<h3>Description</h3> 
				<p>
					{{ mylist.description }}
				</p>
				<div class="resultoption"> 
				{% if user == mylist.created_by %}
				<span> 
					<a href="/app/delete/{{ mylist.slug }}" class="bbtn red" role="button">Delete</a>
				</span> 
				<span> 
					<a href="/app/edit/{{ mylist.slug }}" class="bbtn blue" role="button">Edit</a>
				</span> 
			{% else %}
				<span>
					<a href="/app/notify/{{ mylist.slug }}" class="bbtn turquoise" role="button"> Notify Owner </a>
				</span>
				<span>
					<a onclick="javascript:document.getElementById('overlay').style.display='block';" href="javascript:void(0);" class="bbtn blue" role="button"> Share </a>
				</span>
			{% endif %}
				<span>
					Modified {{ mylist.pub_date|timesince }} ago
				</span>
				</div>
			</div>
	{% endfor %}

	{% else %}
	<div class="confirmbox">
		<p> Awww! 
		</p>
		<p>
			I did not find your search, "{{ query|escape }}", in my system. 
		</p> 
			Are you sure you made no mistake in typing the numbers? 
		<p> 
		<a href="{% url 'home' %}" title="Go to search page" class="bbtn blue large">Try again</a>
		</p>
	</div>
	<center> </center>
	{% endif %}

	{% else %}
	<div class="confirmbox">
		Please, will you search for an IMEI and stop playing around?
		<a href="{% url 'home' %}" title="Go to search page" class="bbtn blue large">Search now!</a>
	</div>
	{% endif %}
{% endblock %}

main/templates/team.html
{% extends 'menpha.html' %}
    <div id="maia-main" role="main">
      <div class="maia-teleport" id="content"></div>
      <div id="fnp-container">
        <div class="maia-cols">
          <div class="maia-col-4" id="top-bg">
            <img alt="" src="statics/fnp-bg-top.jpg">
          </div>
          <div class="maia-col-8">
            <h1 class="maia-display">
              Team Behind Menpha
            </h1>
            <p class="ot-display">
            {% blocktrans %}
              Menpha is an open project developed to gather real information just about any uniquely-identifiable device in the world. With this information in hand, Menpha goes a step further to provide you with its core service of helping you find an item of yours should it get lost or stolen. Menpha does so by allowing any one within its vibrant global community to learn about your lost/stolen item, preventing the resale of it.
            {% endblocktrans %}
            </p>
            <p>
            {% blocktrans %}
              Registration is free and instant. Only the most important personal information about you is required by Menpha. The rest? Keep them in your private bedroom! <a href="">Learn about our privacy and terms</a>
            {% endblocktrans %}
            </p>
            <p>
              <a class="maia-button" data-g-action="Maia: Primary – Content" data-g-event="Maia: Button" data-g-label="Register here" href="http://www.google.com/nonprofits/join/">{% trans "Sign up here" %}</a>
            </p>
          </div>
        </div>
        <div class="maia-cols">
          <div class="maia-col-4" id="pagination-container">
            <div class="pagination-expose">
              <div style="width: 2310px; margin-left: 0px;" class="pagination-scroll">
                <div style="width: 770px;" class="nf-slides">
                  <img alt="" src="statics/fornonprofit_why-1.jpg">
                  <div class="slide-box">
                    <p class="slide-content">
                      Receive notifications about projects you might be interested in based on your
                      donation history.
                    </p><a class="nextFact">Next</a>
                  </div>
                </div>
                <div style="width: 770px;" class="nf-slides">
                  <img alt="" src="statics/fornonprofit_why-2.png">
                  <div class="slide-box">
                    <p class="slide-content">
                      Learn about the project and how your donation will help contribute.
                    </p><a class="nextFact">Next</a>
                  </div>
                </div>
                <div style="width: 770px;" class="nf-slides">
                  <img alt="" src="statics/fornonprofit_why-3.png">
                  <div class="slide-box">
                    <p class="slide-content">
                      Track your donation impact and see how much money has been raised for the
                      projects you’ve donated to.
                    </p><a class="nextFact">Next</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="dot-nav"><a class="current"></a><a class=""></a><a class=""></a></div>
          </div>
          <div class="maia-col-8 fnp-copy-block">
            <div>
              <h2 class="ot-display">
                How does it work?
              </h2>
              <div class="bg-positioner" id="arrow-1">
                <p>
                  <strong>We connect users with causes most likely to interest them.</strong> Each
                  day, the app highlights cool projects from organizations like yours.
                </p>
                <p>
                  <strong>Users donate</strong> to projects they like.
                </p>
              </div>
              <div class="bg-positioner" id="arrow-2">
                <p>
                  <strong>A few dollars become many</strong> as users invite their friends to
                  donate through social media. The more people who donate, the faster your project
                  gets funded.
                </p>
                <p>
                  <strong>Your nonprofit receives monthly project donations</strong> through our
                  partner Network for Good.
                </p>
              </div>
              <div class="bg-positioner top-layer"></div>
            </div>
            <h2 class="ot-display">
              Why should my nonprofit sign up?
            </h2>
            <p>
              <strong>It takes minutes, not months.</strong> Creating projects with One Today only
              requires about ten minutes of planning.
            </p>
            <p>
              <strong>Expand your donor base.</strong> One Today helps you fundraise by introducing
              your projects to people who are more likely to donate to your cause because they, or
              their friends, have donated to similar projects.
            </p>
            <p>
              <strong>Raise awareness about the amazing things you do.</strong> Tell your story to
              new audiences of users who care about the same things that you do.
            </p>
            <p>
              <strong>Create a social movement around your fundraising.</strong> Give your fans and
              followers on social media a new way to show their support.
            </p>
            <p>
              <a class="maia-button" data-g-action="Maia: Primary – Content" data-g-event="Maia: Button" data-g-label="Register here" href="http://www.google.com/nonprofits/join/">Register here</a>
            </p>
          </div>
        </div>
        <p>
          <a href="https://support.google.com/onetoday/" target="_blank">The One Today Nonprofit
          Help Center</a> has more information about how to use your One Today nonprofit account.
        </p>
      </div>
    </div>